version: '3.0'

networks:
  crv_prod_network:
    driver: bridge

services:
  db-prod:
    container_name: mysql-prod
    image: mysql:5.7.17
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./volumes/mysql/prod/database:/var/lib/mysql
      - ./volumes/mysql/prod/conf:/etc/mysql/conf.d
    networks:
      crv_prod_network:
        aliases:
          - mysql
    ports:
# For locale image deploy
      - "3306:3306"
#      - "3306"

  app-prod:
    container_name: symfony-app-prod
    # image: fiser/phpdddstandar-symfony-app:latest
# For locale image deploy
    build:
      context: ../
      dockerfile: ./Docker/app/prod/Dockerfile
    restart: always
    volumes:
      - app_data:/app:rw
      - ./volumes/log/prod/App:/app/App/var/logs
    networks:
      crv_prod_network:
        aliases:
          - app
    env_file:
      - ./.env
    depends_on:
      - db-prod

  compositeui-prod:
    container_name: compositeui-prod
    # image: fiser/phpdddstandar-symfony-app:latest
# For locale image deploy
    build:
      context: ../
      dockerfile: ./Docker/compositeui/prod/Dockerfile
    restart: always
    volumes:
      - app_data:/app:rw
    networks:
      crv_prod_network:
        aliases:
          - composite-ui
    env_file:
      - ./.env

  nginx-prod:
    container_name: nginx-server-prod
    # image: fiser/phpdddstandar-nginx:latest
# For locale image deploy
    build:
      context: nginx/prod
      dockerfile: Dockerfile
    restart: always
    ports:
# For locale image deploy
      - "80:80"
      - "81:81"
#      - "80"
#      - "81"
    volumes:
      - app_data:/app:rw
      - ./volumes/log/prod/Nginx:/var/log/nginx
    depends_on:
      - app-prod
      - compositeui-prod
    networks:
      crv_prod_network:
        aliases:
          - nginx

volumes:
    app_data:
        driver: local